apiVersion: v1
kind: Service
metadata:
  name: newsvc
  labels:
     svclabel: svc
spec:
  type: NodePort
  ports:
    - nodePort: 32077  //Port for Cluster node  
      port: 9000 // Port for Service 
      targetPort: 80  //Pod port
  selector:
    app: webapp
