apiVersion: v1
kind: Service
metadata:
  name: newsvc
  labels:
     svclabel: svc
spec:
  type: NodePort
  ports:          
    - nodePort: 32077 
      port: 9000 
      targetPort: 80
  selector:
    app: webapp
