apiVersion: v1
kind: ReplicationController
metadata:
  name: rc1
  labels:
    type: repcontroller
spec:
  replicas: 5
  template:
    metadata:
      name: firstpod
      labels:
        app: webapp
    spec:
      containers:
        - name: firstcont
          image: nginx