apiVersion: v1
kind: Service
metadata:
  name: repserv
  labels:
    svclab: svc1
spec:
  type: NodePort
  ports:
    - nodePort: 32099
      port: 80
      targetPort: 80
  selector:
    app: webapp    