apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs1
  labels:
    rslabel: rs1
spec:
  replicas: 4
  selector:
    matchLabels:
      type: app
  template:
    metadata:
      name: pod1
      labels:
        type: app
    spec:
      containers:
        - name: cont
          image:  nginx
